name: release

on:
  workflow_call:
    inputs:
      next_version:
        required: true
        type: string
    secrets:
      rubygems-api-key:
        required: true
jobs:
  release:
    uses: metanorma/ci/.github/workflows/rubygems-release.yml@main
    with:
      next_version: ${{ inputs.next_version }}
    secrets:
      rubygems-api-key: ${{ secrets.rubygems-api-key }}
