name: site-deploy

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      concepts-path:
        required: true
        type: string
      production-branch:
        required: true
        type: string
      production-site:
        required: true
        type: string
      staging-branch:
        required: true
        type: string
      staging-site:
        required: true
        type: string
      aws-access-key-id:
        required: true
        type: string
      aws-secret-access-key:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      aws-cf-distribution-id:
        required: true
        type: string
      aws-s3-bucket-name:
        required: true
        type: string
    secrets:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y curl make libxml2-dev libxslt-dev openssl
