name: site-deploy-github-pages

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      repository:
        required: true
        type: string
      concepts-path:
        required: true
        type: string
      breviter-repository:
        required: false
        type: string
      breviter-path:
        required: false
        type: string
      production-branch:
        required: true
        type: string
      production-url:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      environment-name: ${{ steps.prepare.outputs.environment-name }}
      environment-url: ${{ steps.prepare.outputs.environment-url }}
    steps:
    - name: Setup prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y curl make libxml2-dev libxslt-dev openssl libcurl4-openssl-dev

    - name: Prepare environment props
      id: prepare
      run: |
        if [ "${{ inputs.ref }}" = "refs/heads/main" ]; then
          environment_name="production"
          environment_url="${{ inputs.production-url }}"
        else
          environment_name=skip
          environment_url=missing
        fi

        echo "environment-url=${environment_url}" >> $GITHUB_OUTPUT
        echo "environment-name=${environment_name}" >> $GITHUB_OUTPUT

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}

    - name: Use Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Checkout data
      uses: actions/checkout@v3
      with:
        token: ${{ github.token }}
        repository: ${{ inputs.repository }}
        path: ${{ inputs.concepts-path }}
        ref: ${{ steps.prepare.outputs.environment-name == 'skip' && inputs.production-branch || inputs.ref }}
        fetch-depth: 1

    - name: Checkout breviter
      if: inputs.breviter-repository != ''
      uses: actions/checkout@v3
      with:
        token: ${{ github.token }}
        repository: ${{ inputs.breviter-repository }}
        path: ${{ inputs.breviter-path }}
        ref: main
        fetch-depth: 1
        submodules: true

    - name: Cache relaton
      uses: actions/cache@v3
      with:
        path: relaton
        key: ${{ runner.os }}-${{ hashFiles(join(inputs.concepts-path, '/**/*.yaml')) }}

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3

    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: '12'
        cache: 'npm'

    - run: npm install

    - name: Build site
      run: make _site

    - name: Compress files
      run: zip -9 -r site.zip _site

    - uses: actions/upload-artifact@v3
      if: steps.prepare.outputs.environment-name != 'skip'
      with:
        name: site
        path: site.zip

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: _site

  deploy:
    if: needs.build.outputs.environment-name != 'skip'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ needs.build.outputs.environment-name }}
      url: ${{ needs.build.outputs.environment-url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2